# vim: foldmethod=marker

Normal = { fg = "fg1", bg = "bg0" }
Bold = { fg = "fg0", gui = "bold" }
Accent = { fg = "purple" }
AccentBold = { fg = "purple", gui = "bold" }
MutedFg = { fg = "fg4" }
MutedBg = { fg = "bg4" }


# Colorscheme {{{1

# Highlight Groups (`:help highlight-groups`) {{{2
ColorColumn = { bg = "bg1" }
Conceal = { fg = "blue", bg = "NONE" }
CursorColumn = { link = "CursorLine" }
CursorLine = { bg = "bg2" }
CursorLineNr = { link = "Accent" }
DiffAdd = { fg = "green", bg = "bg0", gui = "inverse" }
DiffChange = { fg = "aqua", bg = "bg0", gui = "inverse" }
DiffDelete = { fg = "red", bg = "bg0", gui = "inverse" }
DiffText = { fg = "yellow", bg = "bg0", gui = "inverse" }
Directory = { link = "Accent" }
ErrorMsg = { fg = "bg0", bg = "red", gui = "bold" }
FoldColumn = { fg = "gray", bg = "bg1" }
Folded = { fg = "gray", bg = "sign" }
IncSearch = { fg = "orange", bg = "bg0", gui = "inverse" }
LineNr = { link = "MutedBg" }
MatchParen = { link = "AccentBold" }
ModeMsg = { link = "AccentBold" }
MoreMsg = { link = "AccentBold" }
NonText = { link = "MutedBg" }
NormalNC = { link = "MutedFg" }
Pmenu = { fg = "fg1", bg = "bg2" }
PmenuSbar = { bg = "bg2" }
PmenuSel = { fg = "bg2", bg = "purple", gui = "bold" }
PmenuThumb = { bg = "bg4" }
Question = { link = "AccentBold" }
QuickFixLine = { fg = "bg0", bg = "purple", gui = "bold" }
Search = { fg = "purple", bg = "bg0", gui = "inverse" }
SignColumn = { fg = "NONE", bg = "sign" }
SpecialKey = { link = "MutedFg" }
SpellBad = { gui = "undercurl", guisp = "red" }
SpellCap = { gui = "undercurl", guisp = "blue" }
SpellLocal = { gui = "undercurl", guisp = "aqua" }
SpellRare = { gui = "undercurl", guisp = "purple" }
StatusLine = { fg = "bg2", bg = "fg1", gui = "inverse" }
StatusLineNC = { fg = "bg1", bg = "fg4", gui = "inverse" }
TabLine = { fg = "bg4", bg = "bg1", gui = "NONE" }
TabLineFill = { link = "TabLine" }
TabLineSel = { fg = "purple", bg = "bg1", gui = "bold" }
TermCursorNC = { link = "IncSearch" }
Title = { link = "AccentBold" }
Visual = { bg = "bg3", gui = "inverse" }
WarningMsg = { fg = "red", gui = "bold" }
WildMenu = { link = "PmenuSel" }
WinSeparator = { link = "MutedBg" }

# Syntax (`:help group-name`) {{{2
Comment = { fg = "gray" }
Constant = { link = "Normal" }
String = { fg = "blue" }
Identifier = { link = "Normal" }
Statement = { link = "Bold" }
PreProc = { link = "Bold" }
Type = { link = "Normal" }
Special = { link = "Normal" }
Underlined = { fg = "fg1", gui = "underline" }
Error = { fg = "red", bg = "bg0", gui = "bold,inverse" }
Todo = { link = "AccentBold" }

# Extra tree-sitter highlights  {{{2
"@text.diff.add" = { fg = "green" }
"@text.diff.delete" = { fg = "red" }

# git/diff highlights {{{1
diffAdded = { fg = "green" }
diffRemoved = { fg = "red" }
gitCommitOverflow = { link = "Error" }

GitSignsAdd = { fg = "green", bg = "sign" }
GitSignsChange = { fg = "purple", bg = "sign" }
GitSignsDelete = { fg = "red", bg = "sign" }
