# vim: foldmethod=marker

Normal = { fg = "fg2", bg = "bg0" }

BaseFg = { fg = "fg2" }
Bold = { fg = "fg0", gui = "bold" }
Accent = { fg = "aqua" }
AccentBold = { fg = "aqua", gui = "bold" }
MutedFg = { fg = "fg4" }
MutedBg = { fg = "bg4" }


# Colorscheme {{{1

# Highlight Groups (`:help highlight-groups`) {{{2
ColorColumn = { bg = "bg1" }
Conceal = { fg = "blue", bg = "NONE" }
CurSearch = { fg = "yellow", bg = "bg0", gui = "inverse" }
CursorColumn = { link = "CursorLine" }
CursorLine = { bg = "bg2" }
CursorLineFold = { link = "FoldColumn" }
CursorLineNr = { link = "Accent" }
CursorLineSign = { link = "SignColumn" }
DiffAdd = { fg = "green", bg = "bg0", gui = "inverse" }
DiffChange = { fg = "purple", bg = "bg0", gui = "inverse" }
DiffDelete = { fg = "red", bg = "bg0", gui = "inverse" }
DiffText = { fg = "yellow", bg = "bg0", gui = "inverse" }
Directory = { link = "Accent" }
EndOfBuffer = { link = "NonText" }
ErrorMsg = { fg = "bg0", bg = "red", gui = "bold" }
FloatBorder = { link = "NormalFloat" }
FloatFooter = { link = "FloatTitle" }
FloatTitle = { fg = "aqua", bg = "bg1", gui = "bold" }
FoldColumn = { fg = "gray", bg = "bg1" }
Folded = { fg = "gray", bg = "sign" }
IncSearch = { link = "CurSearch" }
LineNr = { link = "MutedBg" }
MatchParen = { link = "AccentBold" }
ModeMsg = { link = "AccentBold" }
MoreMsg = { link = "AccentBold" }
MsgArea = { link = "Normal" }
MsgSeparator = { link = "StatusLine" }
NonText = { link = "MutedBg" }
NormalFloat = { fg = "fg1", bg = "bg1" }
NormalNC = { link = "MutedFg" }
Pmenu = { fg = "fg1", bg = "bg2" }
PmenuExtra = { link = "Pmenu" }
PmenuExtraSel = { link = "PmenuSel" }
PmenuKind = { link = "Pmenu" }
PmenuKindSel = { link = "PmenuSel" }
PmenuSbar = { bg = "bg2" }
PmenuSel = { fg = "bg2", bg = "aqua", gui = "bold" }
PmenuThumb = { bg = "bg4" }
Question = { link = "AccentBold" }
QuickFixLine = { fg = "bg0", bg = "aqua", gui = "bold" }
Search = { fg = "aqua", bg = "bg0", gui = "inverse" }
SignColumn = { fg = "NONE", bg = "sign" }
SnippetTabstop = { link = "Visual" }
SpecialKey = { link = "MutedFg" }
SpellBad = { gui = "undercurl", guisp = "red" }
SpellCap = { gui = "undercurl", guisp = "blue" }
SpellLocal = { gui = "undercurl", guisp = "aqua" }
SpellRare = { gui = "undercurl", guisp = "purple" }
StatusLine = { fg = "bg2", bg = "fg1", gui = "inverse" }
StatusLineNC = { fg = "bg1", bg = "fg4", gui = "inverse" }
Substitute = { link = "IncSearch" }
TabLine = { fg = "bg4", bg = "bg1", gui = "NONE" }
TabLineFill = { link = "TabLine" }
TabLineSel = { fg = "aqua", bg = "bg1", gui = "bold" }
Title = { link = "AccentBold" }
Visual = { bg = "bg3", gui = "inverse" }
WarningMsg = { fg = "red", gui = "bold" }
WhiteSpace = { link = "NonText" }
WildMenu = { link = "PmenuSel" }
WinBar = { link = "StatusLine" }
WinBarNC = { link = "StatusLineNC" }
WinSeparator = { link = "MutedBg" }

# Syntax (`:help group-name`) {{{2
Comment = { link = "Accent" }
Constant = { link = "BaseFg" }
String = { fg = "blue" }
Identifier = { link = "BaseFg" }
Function = { link = "Identifier" }
Statement = { link = "Bold" }
Operator = { link = "MutedFg" }
PreProc = { link = "BaseFg" }
Type = { link = "BaseFg" }
Special = { link = "BaseFg" }
Delimiter = { link = "MutedFg" }
Underlined = { fg = "fg1", gui = "underline" }
Error = { fg = "red", bg = "bg0", gui = "bold,inverse" }
Todo = { link = "AccentBold" }
Added = { fg = "green" }
Changed = { fg = "purple" }
Removed = { fg = "red" }

# Diagnostic (`:help diagnostic-highlights`) {{{2
DiagnosticError = { fg = "red" }
DiagnosticWarn = { link = "DiagnosticError" }
DiagnosticInfo = { link = "DiagnosticError" }
DiagnosticHint = { link = "DiagnosticError" }
DiagnosticOk = { link = "DiagnosticError" }
DiagnosticSignError = { fg = "red", bg = "sign" }
DiagnosticSignWarn = { link = "DiagnosticSignError" }
DiagnosticSignInfo = { link = "DiagnosticSignError" }
DiagnosticSignHint = { link = "DiagnosticSignError" }
DiagnosticSignOk = { link = "DiagnosticSignError" }
DiagnosticUnderlineError = { gui = "underline", guisp = "red" }
DiagnosticUnderlineWarn = { link = "DiagnosticUnderlineError" }
DiagnosticUnderlineInfo = { link = "DiagnosticUnderlineError" }
DiagnosticUnderlineHint = { link = "DiagnosticUnderlineError" }
DiagnosticUnderlineOk = { link = "DiagnosticUnderlineError" }
DiagnosticUnnecessary = { link = "MutedFg" }

# tree-sitter highlights (`:help treesitter-highlight-groups`) {{{2
"@comment.error" = { link = "@comment.todo" }
"@comment.note" = { link = "@comment.todo" }
"@comment.warning" = { link = "@comment.todo" }
"@markup.raw" = { fg = "blue" }
"@punctuation.special" = { link = "@punctuation" }
"@string.documentation" = { link = "Comment" }
"@string.special.url.comment" = { fg = "aqua", gui = "underline" }
"@tag.delimiter" = { link = "MutedFg" }
"@variable" = { link = "Identifier" }

# Custom highlights {{{2
"RafikDefinition" = { fg = "purple" }
"@rafik.definition" = { link = "RafikDefinition" }

# Plugins {{{1

# GV and git-messenger {{{2
diffAdded = { link = "Added" }
diffChanged = { link = "Changed" }
diffRemoved = { link = "Removed" }

# mini {{{2
MiniDiffSignAdd = { fg = "green", bg = "sign" }
MiniDiffSignChange = { fg = "purple", bg = "sign" }
MiniDiffSignDelete = { fg = "red", bg = "sign" }
